inputs: inputs/attack_sample_inputs.txt
input_dir: "datasets/asvspoofWavs"
ref_dir: datasets/asvspoofWavs
lengths: inputs/lengths
model_maps: inputs/configMap.yaml

seed: 0000
sr: 16000
system: ADVSR
attack_type:  CM_Attack #TIME_DOMAIN_ATTACK, auto_pgd #carlini #CM_Attack #boundary #carlini
num_samples:  10
silence_threshold: "-25.0"
log_interval: 1
perf_log: perf.txt
print_iter_out: True
write_wavs: True
write_plots: False

shadow:
    cm: "dev"
    asv: "dev"
target: 
    cm: "train"
    asv: "train"

loss: null

discriminator_wb: 
    args: 
        cm: #ignored for ADVSR
            selector: [lcnnFull]
            lambda: 3 #ignored for ADVSR, ADVCM
        asv: #ignored for ADVCM
            selector: [mfcc]
            lambda: 1 #ignored for ADVSR, ADVCM

discriminators:
    args:
        cm: #ignored for ADVSR
            selector: [WAV2VEC, SSNet, lcnnFull, rawGAT_st, mcg, mlcg, Res2Net, AIR, darts, comparative, RawDarts, AASSIST, AASSIST-L, AIR_AM]  
        asv: #ignored for ADVCM
            selector: [mfcc, lps]

TIME_DOMAIN_ATTACK:
    epsilon: 0.0015
    max_iter: 5
    norm: null
    restarts: 8

auto_pgd:
    eps: 0.003
    eps_step: 0.0003
    max_iter: 100
    targeted: true
    nb_random_init: 5
    batch_size: 1

carlini:
    targeted: true
    max_iter: 20
    confidence: 0.0
    learning_rate: 0.01
    binary_search_steps: 10
    max_halving: 10 
    max_doubling: 10

CM_Attack:
    first_layer:  
        type: "TIME_DOMAIN_ATTACK"
        args:  
            epsilon: 0.0035
            max_iter: 0
            restarts: 1
    last_layer: null
    mid_layers: [
            {'type': STFT_Attack,
                  'args': {
                          epsilon: 0.000005,
                          max_iter: 0,
                          nfft: 1024,
                          window: 'kaiser_window',
                          hop_length: 512,
                          win_length: 1024,
                          restarts: 5,
                          delta: 0,
                          }
             }
                ]
    itrs: 3
    alpha_factors:
        STFT_Attack: 4
    powers:
        STFT_Attack: 0.98
    r_c:
        stationary: true
        win: 'hann_window'
        n_fft: 512
        hop_length: 128
        win_length: 512
        freq_mask_smooth_hz: 500
        time_mask_smooth_ms: 100 
        padding: 45000
    stop_reduce: 6
    r_div: 10
    k_div: 3.4 #best: 1.1*stacks - 1
    stacks: 4
    interval: 1
    optim_sat: 15
    stationary: true
    apply_args_to_layers: all_but_last
    verbose: 1

r_args:
    p: null
    n_std_thresh_stationary: 1.5
